[workspace]
  members = ["podtest-core", "podtest-postgresql", "podtest-mysql", "podtest-redis"]
  build-members = ["podtest-core", "podtest-postgresql", "podtest-mysql", "podtest-redis"]
  test-members = []
